services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - THREATVAULT_REDIS_URL=redis://redis:6379/0
      - THREATVAULT_CELERY_BROKER_URL=redis://redis:6379/1
      - THREATVAULT_CELERY_RESULT_BACKEND=redis://redis:6379/2
      - THREATVAULT_ENABLE_CACHE=true
      - THREATVAULT_DEMO_MODE=true
    volumes:
      - uploads:/app/uploads
    depends_on:
      - redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A app.workers.celery_app worker -l info -Q sandbox,static -c 4
    environment:
      - THREATVAULT_CELERY_BROKER_URL=redis://redis:6379/1
      - THREATVAULT_CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - redis
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  uploads:
  redis_data:
